name: Publish Observable Framework Site

on:
  workflow_dispatch:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      # Create .nojekyll file to bypass Jekyll processing
      - name: Create .nojekyll file
        run: touch .nojekyll

      - name: Build
        run: npm run build

      # Debug step to verify data files are in the build output
      - name: List files in dist directory
        run: |
          echo "Contents of dist directory:"
          ls -la dist
          echo "Contents of dist/data directory (if exists):"
          ls -la dist/data || echo "dist/data directory does not exist"
          echo "Contents of dist/_file directory (if exists):"
          ls -la dist/_file || echo "dist/_file directory does not exist"

      # Create .nojekyll file in the dist directory
      - name: Create .nojekyll in dist
        run: touch dist/.nojekyll

      # Copy CSV files to both possible locations
      - name: Ensure data files are copied
        run: |
          # For original path
          if [ ! -d "dist/data" ]; then
            mkdir -p dist/data
            cp -r src/data/* dist/data/
            echo "Manually copied data files to dist/data"
          fi
          
          # For _file path (where Observable Framework might put them)
          if [ -d "dist/_file" ]; then
            # Find all CSV files in the source data directory
            find src/data -name "*.csv" -exec cp {} dist/_file/ \;
            echo "Copied CSV files to dist/_file directory"
          elif [ -d "dist/_file/data" ]; then
            # If there's a nested data directory in _file
            find src/data -name "*.csv" -exec cp {} dist/_file/data/ \;
            echo "Copied CSV files to dist/_file/data directory"
          else
            # Create _file directory if it doesn't exist
            mkdir -p dist/_file
            find src/data -name "*.csv" -exec cp {} dist/_file/ \;
            echo "Created dist/_file and copied CSV files"
          fi
          
          # Print the contents of directories to verify
          echo "After copying, contents of dist/_file:"
          ls -la dist/_file || echo "dist/_file directory does not exist"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 